<a href="https://colab.research.google.com/github/zgturn/MAT-422/blob/main/Section_1_2_Zachary_Turner.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **Section 1.2: Elements of Linear Algebra**

We only consider the case of the linear space $V = \mathbb{R}^n$.

### **1.2.1: Linear Spaces**
**Definition** (Linear subspace): A linear subspace of $V$ is a subset $U \subseteq V$ such that for all $\textbf{u}_1, \textbf{u}_2 \in U$ and $\alpha \in \mathbb{R}$, we have that
$$\textbf{u}_1 + \textbf{u}_2 \in U$$ and
$$\alpha\textbf{u}_1 \in U.$$

**Definition** (Span) Let $\textbf{w}_1, \dots, \textbf{w}_m \in V$. The span of $\{\textbf{w}_1, \dots, \textbf{w}_m\}$ is the set of all linear combinations of the $\textbf{w}_j$'s, denoted $\text{span}(\textbf{w}_1, \dots, \textbf{w}_m)$

The span of these vectors form a linear subspace.

**Definition** (Linear independence): A list of vectors $\textbf{u}_1, \dots, \textbf{u}_m$ is linearly independent if and only if
$$\sum_{j = 1}^m \alpha_j\textbf{u}_j = \textbf{0} \implies \alpha_j = 0$$
for all $j$.

This concept of linear independence and span lead to an important concept: the basis of a linear space.

**Definition** (Basis) Let $U$ be a linear subspace of $V$. We say that a list of vectors $\textbf{u}_1, \dots, \textbf{u}_m \in U$ forms a basis of $U$ if

(1) $ \text{span}(\textbf{u}_1, \dots, \textbf{u}_m) = U$ and

(2) $ \textbf{u}_1, \dots, \textbf{u}_m$ are linearly independent.

Every basis of $U$ has the same number of elements. We call this number the dimension of $U$, denoted $\text{dim}(U)$.



### **1.2.2: Orthogonality**

#### **_1.2.2.1: Orthogonal Bases_**
**Definition** (Norm and inner product): $\langle\textbf{u}, \textbf{v} \rangle = \textbf{u} \cdot \textbf{v} = \sum_i u_iv_i$ and $||u|| = \sqrt{\sum_i u_i^2}$.

**Definition** (Orthonormality): A list of vectors $\textbf{u}_1, \dots, \textbf{u}_m$ is orthonormal if $\langle \textbf{u}_i, \textbf{u}_k \rangle = 0$ and $||\textbf{u}_i|| = 1$ for all $i$ and $j \neq i$

**Lemma** (Properties of orthonormal vectors): Let $\textbf{u}_1, \dots, \textbf{u}_m$ be a list of orthonormal vectors. Then

(1) $||\sum_j \alpha_j\textbf{u}_j||^2 = \sum_j \alpha_j^2$ and

(2) $\textbf{u}_1, \dots, \textbf{u}_m$ are linearly independent

Usually, it is not obvious how to find the coordinates of a vector $\textbf{w}$ in a subspace $U$ given a basis. However, if one has an orthonormal basis, it becomes easy.

**Theorem** (Orthonormal basis expansion): Let $\textbf{q}_1, \dots, \textbf{q}_m$ be an orthonormal basis of a linear space $U$, and let $\textbf{u} \in U$. Then
$$\textbf{u} = \sum_{j = 1}^m \langle \textbf{u}, \textbf{q}_j \rangle \textbf{q}_j.$$

#### **_1.2.2.2: Best Approximation Theorem_**

A lot of optimization problems can be boiled down to a simple linear algebra problem. Suppose we have a linear subspace $U \subseteq V$ and a vector $\textbf{v} \notin U$. Despite this, we still want to find the vector $\textbf{v}^* \in U$ that is the _closest_ in distance to $\textbf{v}$. This defines the optimization problem

$$\text{min}_{\textbf{v}^* \in U} ||\textbf{v}^* - \textbf{v}||.$$

**Definition** (Orthogonal projection): Let $U \subseteq V$ be a linear subspace with orthonormal basis $\textbf{q}_1, \dots, \textbf{q}_m$. The orthogonal projection of $\textbf{v} \in V$ on $U$ is defined as
$$P_U\textbf{v} = \sum_{j = 1}^m \langle \textbf{v}, \textbf{q}_j \rangle \textbf{q}_j.$$

With the orthogonal projection in hand, we can solve the above approximation problem: the vector in $\textbf{v}^* \in U$ closest in distance to $\textbf{v}$ is $P_U\textbf{v}$. We summarize the result with a theorem.

**Theorem** (Best approximation theorem): Let $U \subset V$ be a linear subspace with orthonormal basis $\textbf{q}_1, \dots, \textbf{q}_m$ and let $\textbf{v} \in V$. Then for any $\textbf{u} \in U$, we have that
$$||\textbf{v} - P_U\textbf{v}|| \leq ||\textbf{v} - \textbf{u}||,$$
with equality if $\textbf{u} = P_u\textbf{v}$.

**Lemma** (Orthogonal decomposition): Let $U \subseteq V$ be a liear subspace with orthonormal basis $\textbf{q}_1, \dots, \textbf{q}_m$ and let $\textbf{v} \in V$. Then for any $\textbf{u} \in U$, we have that $\langle \textbf{v} - P_U\textbf{v}, \textbf{u} \rangle = 0$. Moreover, $\textbf{v}$ can be decomposed as $(\textbf{v} - P_U\textbf{v}) + P_U\textbf{v}$, with the two terms being orthogonal.

We can create a projection matrix with the following method. Let $\textbf{q}_1, \dots, \textbf{q}_m$ be an orthonormal basis, and set $Q = (\textbf{q}_1 \cdots \textbf{q}_m)$. We note that $Q^T\textbf{v} = (\langle \textbf{v}, \textbf{q}_1 \rangle \cdots \langle \textbf{v}, \textbf{q}_m \rangle)^T$ lists the coefficients in the exansion of $P_U\textbf{v}$ over the basis $\textbf{q}_1, \dots, \textbf{q}_m$. Hence, we have that $P = QQ^T$ provides the projection of any vector $\textbf{v} \in V$ onto $U$.

### **1.2.3: Gram-Schmidt Process**

The Gram-Schmidt process is an algorithm that, given any basis, can be used to find another orthonormal basis. Let $\textbf{u}_1, \dots, \textbf{u}_m$ be linearly independent vectors. Suppose we want to find an orthonormal basis to represent $\text{span}(\textbf{u}_1, \dots, \textbf{u}_m) = U$. The process can be explained as follows: we start with the vector $\textbf{u_1}$, and for each consective vector, take away the orthogonal projection of the previous iterations.

To generate an orthonormal basis, set $\textbf{v}_1 = \textbf{u}_1$ and $\textbf{q}_1 = \frac{\textbf{v}_1}{||\textbf{v}_1||}$. Then we set $\textbf{v}_2 = \textbf{u}_2 - \langle \textbf{u}_1, \textbf{q}_1 \rangle\textbf{q}_1$ and $\textbf{q}_2 = \frac{\textbf{v}_2}{||\textbf{v}_2||}$. In general, for $i \in \{1, \dots, m\}$, we have that $\textbf{v}_i = \textbf{u}_i - \sum_{j=1}^{i-1}\langle \textbf{u}_j, \textbf{q}_j \rangle\textbf{q}_j$. The list of vectors $\textbf{q}_1, \dots, \textbf{q}_m$ is orthonormal, and $\text{span}(\textbf{u}_1, \dots, \textbf{u}_m) = \text{span}(\textbf{q}_1, \dots, \textbf{q}_m)$.

In [ ]:
import numpy as np

# Given an matrix A with columns as the basis of a space, it returns a matrix with
# columns as the orthonormal basis
def gram_schmidt(A):
  (n, m) = A.shape
  A_orthogonal = A

  for i in range(m):
    u = A[:, i]
    proj = np.zeros([n])

    if i >= 1:
      for j in range(i):
        proj = proj - np.dot(A[:, i], A_orthogonal[:, j])*A_orthogonal[:, j]

    v = u + proj
    q = v / np.linalg.norm(v)

    A_orthogonal[:, i] = q

  return A_orthogonal

A = np.array([[4.0, -1.0, 0.0], [2.0, 3.0, 5.0], [-1.0, 7.0, 2.0]])
A_orthogonal = gram_schmidt(A)

print(A_orthogonal)

[[ 0.87287156 -0.00626298 -0.48790984]
 [ 0.43643578  0.45719752  0.77491563]
 [-0.21821789  0.88934313 -0.4018081 ]]


### **1.2.4: Eigenvalues and Eigenvectors**

#### **_1.2.4.1: Eigenvalues, Eigenvectors, and Diagnalization_**

**Definition** (Eigenvalues and eigenvectors): Let $A \in \mathbb{R}^{n \times n}$. Then $\lambda \in \mathbb{R}$ is an _eigenvalue_ of $A$ if there exists $\textbf{x} \in \mathbb{R}^n \setminus{\{\textbf{0}\}}$ such that
$$A\textbf{x} = \lambda\textbf{x}.$$
We call $\textbf{x}$ an _eigenvector_. The span of an eigenvector is called an _eigenspace_.

Any square matrix $A \in \mathbb{R}^{n \times n}$ has at most $n$ eigenvalues. Moreover, two eigenvectors $\textbf{x}_i$ and $\textbf{x}_j$ corresponding to distinct eigenvalues $\lambda_i$ and $\lambda_j$ are linearly independent of each other.

If $A$ has $n$ distinct eigenvalues, then we can represent $A$ as
$$A = PDP^{-1},$$
where $D = \text{diag}(\lambda_1, \dots, \lambda_n)$ and $P = (\textbf{x}_1 \dots \textbf{x}_n)$. In this case, we say that $A$ is _diagonalizable_.

**Theorem**: If $A$ is symmetric, then any two eigenvectors from different eigenspaces are orthogonal.

A matrix $A$ is said to be orthogonally diagonalizable if there is an orthogonal matrix $P$ (i.e. $P^{-1} = P^T$) and a diagonal matrix $D$ such that
$$A = PDP^T = PDP^{-1}.$$

**Theorem** (The spectral theorem for symmatric matrices): An $n \times n$ symmetric matric $A$ has the following properties:

1) $A$ has $n$ real eigenvalues, counting multiplicities.

2) If $\lambda$ is an eigenvalue of $A$ with multiplicity $k$, then the eigespace for $\lambda$ is $k$-dimensional.

3) The eigenspaces are mutually orthogonal, in the sense that eigenvectors corresponding to different eigenvalues are orthogonal.

4) $A$ is orthogonally diagonalizable.



In [ ]:
import numpy as np

# In the case of a non-symmetric matrix

A = np.array([[4.0, -1.0, 0.0], [2.0, 3.0, 5.0], [-1.0, 7.0, 2.0]])

lam, P = np.linalg.eig(A)

print('The eigenvalues of A are: \n', lam)
print('\nThe corresponding eigenvectors of A are:\n ', P)

D = np.zeros([3, 3])
for i in range(A.ndim+1):
  D[i, i] = lam[i]

print('\nComputing A from its diagonalization:\n', np.matmul(np.matmul(P, D), np.linalg.inv(P)))


The eigenvalues of A are: 
 [-3.25431586  3.96784095  8.28647491]

The corresponding eigenvectors of A are:
  [[ 0.08351193  0.93004426 -0.1512737 ]
 [ 0.60582193  0.02990934  0.64843091]
 [-0.79120512 -0.36622821  0.74609223]]

Computing A from its diagonalization:
 [[ 4.00000000e+00 -1.00000000e+00  1.54651897e-15]
 [ 2.00000000e+00  3.00000000e+00  5.00000000e+00]
 [-1.00000000e+00  7.00000000e+00  2.00000000e+00]]


In [ ]:
# In the case of a symmetric matrix

A = np.array([[1, 2, 3], [2, 1, 2], [3, 2, 1]])

lam, P = np.linalg.eig(A)

print('The eigenvalues of A are: \n', lam)
print('\nThe corresponding eigenvectors of A are:\n ', P)

D = np.zeros([3, 3])
for i in range(A.ndim+1):
  D[i, i] = lam[i]

print('\nComputing A from its diagonalization:\n', np.matmul(np.matmul(P, D), np.linalg.inv(P)))

# Eigenvectors from different eigenspaces are orthogonal
print('\nComputing the inner product of x_1 and x_2, corresponding to lambda_1 and lambda_2:\n', np.dot(P[:, 0], P[:, 1]))
print('\nThe norm of x_1:', np.linalg.norm(P[:, 0]))

The eigenvalues of A are: 
 [ 5.70156212 -2.         -0.70156212]

The corresponding eigenvectors of A are:
  [[-6.05912800e-01 -7.07106781e-01  3.64512933e-01]
 [-5.15499134e-01  1.47635207e-16 -8.56890100e-01]
 [-6.05912800e-01  7.07106781e-01  3.64512933e-01]]

Computing A from its diagonalization:
 [[1. 2. 3.]
 [2. 1. 2.]
 [3. 2. 1.]]

Computing the inner product of x_1 and x_2, corresponding to lambda_1 and lambda_2:
 -2.220446049250313e-16

The norm of x_1: 1.0


#### **_1.2.4.2: Constrained Opimization_**

The following is useful for many optimization problems.

**Theorem**: Let $A$ be an $n \times n$ symmetric matrix $A$ with an orthogonal diagonalization $A = PDP^{-1}$. The columns of $P$ are orthonormal eigenvectors $\textbf{x}_1, \dots, \textbf{x}_n$ of $A$. Assume that the diagonals of $D$ are arranged so that $\lambda_1 \leq \lambda_2 \leq \dots \leq \lambda_n$. Then
$$\text{min}_{\textbf{x} \neq 0}\frac{\textbf{x}^TA\textbf{x}}{\textbf{x}^T\textbf{x}} = \lambda_1$$
is achieved when $\textbf{x} = \textbf{x}_1$ and
$$\text{max}_{\textbf{x} \neq 0}\frac{\textbf{x}^TA\textbf{x}}{\textbf{x}^T\textbf{x}} = \lambda_n$$
is achieved when $\textbf{x} = \textbf{x}_n$.